---
- name: Download sops release
  ansible.builtin.get_url:
    url: "{{ sops_download }}"
    dest: "{{ sops_path }}/sops"
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  tags:
    - sops

...
